# Generated by Django 4.1.13 on 2024-12-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_code', models.IntegerField(default=0)),
                ('original_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('product_qty', models.IntegerField(default=0)),
            ],
        ),
    ]
